fn main() {
    // tauri-build (below) sets the `desktop`/`mobile` cfgs on gui builds; the
    // core also reads them (rpc "desktop" flag) on default builds, where
    // they'd otherwise warn as unexpected.
    println!("cargo:rustc-check-cfg=cfg(desktop, mobile)");
    // Only the Tauri (gui) build needs codegen from tauri.conf.json; the
    // default CLI build does nothing here.
    #[cfg(feature = "gui")]
    tauri_build::build();

    // Generate the shell module inventory from the files on disk, so a new
    // src/shell/js/*.js is served by the native shell without anyone editing a
    // hand-kept list in server.rs (adding one there used to be a silent 404).
    generate_shell_modules();
}

fn generate_shell_modules() {
    use std::fmt::Write as _;
    let mut entries: Vec<(String, String)> = Vec::new();
    let base = std::path::Path::new("src/shell/js");
    let mut dirs = vec![base.to_path_buf()];
    while let Some(dir) = dirs.pop() {
        let mut names: Vec<_> = std::fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
            .map(|e| e.unwrap().path())
            .collect();
        names.sort();
        for path in names {
            if path.is_dir() {
                dirs.push(path);
            } else if path.extension().and_then(|e| e.to_str()) == Some("js") {
                let rel = path.strip_prefix(base).unwrap().to_string_lossy().replace('\\', "/");
                let inc = path.to_string_lossy().replace('\\', "/");
                entries.push((rel, inc));
                println!("cargo:rerun-if-changed={}", path.display());
            }
        }
    }
    println!("cargo:rerun-if-changed=src/shell/js");
    let mut out = String::from("// @generated by build.rs from src/shell/js/**.js
");
    out.push_str("pub const SHELL_MODULES: &[(&str, &str)] = &[
");
    for (rel, inc) in &entries {
        writeln!(out, "    ({rel:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{inc}\"))),").unwrap();
    }
    out.push_str("];
");
    let dst = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("shell_modules.rs");
    std::fs::write(dst, out).unwrap();
}

