#!/usr/bin/env node
// Regenerates src/shell/icons.js from lucide-static (unpkg).
//
//   node scripts/fetch-icons.mjs            # rebuild with the list below
//   node scripts/fetch-icons.mjs plus minus # add names to the list and rebuild
//
// The ICONS list is the source of truth for what ships in the shell. After
// building, the script greps shell.js/index.html for icon names used via
// uappIcon()/I() and data-dlg-icon and fails if any are missing from the list.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src", "shell", "icons.js");

const ICONS = [
  "archive", "arrow-left", "arrow-right", "arrow-up", "book-open", "bot",
  "brain", "chart-column", "check", "chevron-left", "chevron-right",
  "circle-alert", "circle-help", "circle-plus", "code", "compass", "copy",
  "database", "download", "ellipsis-vertical", "eraser", "external-link",
  "eye", "eye-off", "file", "file-code", "file-pen", "file-plus",
  "file-question", "file-text", "file-type", "files", "film", "folder",
  "folder-input", "folder-open", "folder-plus", "globe", "hard-drive", "history", "image",
  "layout-grid", "link", "list", "list-filter", "message-square", "minus",
  "music", "package", "panel-right-close", "paperclip", "pencil",
  "pencil-line", "play", "plug-zap", "plus", "puzzle", "refresh-cw",
  "rotate-cw", "save", "search", "send-horizontal", "server", "settings",
  "shield-alert", "shield-check", "smartphone", "square", "square-terminal",
  "table-2", "trash-2", "type", "upload", "wrench", "x", "zap",
];

const extra = process.argv.slice(2).filter((n) => !ICONS.includes(n));
const names = [...ICONS, ...extra].sort();

async function fetchIcon(name) {
  const url = `https://unpkg.com/lucide-static/icons/${name}.svg`;
  const r = await fetch(url, { redirect: "follow" });
  if (!r.ok) throw new Error(`${name}: HTTP ${r.status} from ${url}`);
  const svg = await r.text();
  const m = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!m) throw new Error(`${name}: no <svg> in response`);
  return m[1].replace(/<!--[\s\S]*?-->/g, "").replace(/\n\s*/g, "").trim();
}

const entries = [];
for (const name of names) {
  entries.push([name, await fetchIcon(name)]);
  process.stdout.write(".");
}
process.stdout.write("\n");

const body = entries.map(([n, p]) => `${JSON.stringify(n)}:${JSON.stringify(p)}`).join(",");
const js = `/* Embedded lucide icons (ISC license, lucide.dev). Monochrome, stroke=currentColor.
 * GENERATED by scripts/fetch-icons.mjs — edit the list there, not this file. */
(() => {
  const paths = {${body}};
  window.uappIcon = (name, size = 16) => {
    const p = paths[name] || paths["wrench"];
    return \`<svg xmlns="http://www.w3.org/2000/svg" width="\${size}" height="\${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">\${p}</svg>\`;
  };
})();
`;
writeFileSync(OUT, js);
console.log(`wrote ${OUT} (${names.length} icons)`);

// Guard: every icon name the shell references must be in the list.
const { readdirSync } = await import("node:fs");
const shellFiles = ["index.html",
  ...readdirSync(join(ROOT, "src", "shell", "js")).map((f) => join("js", f))];
const used = new Set();
for (const f of shellFiles) {
  const src = readFileSync(join(ROOT, "src", "shell", f), "utf8");
  for (const m of src.matchAll(/(?:uappIcon|\bI)\(\s*"([a-z0-9-]+)"/g)) used.add(m[1]);
  for (const m of src.matchAll(/data-dlg-icon="([a-z0-9-]+)"/g)) used.add(m[1]);
  // icon names kept in lookup tables ({ icon: "name" } / ICON maps)
  for (const m of src.matchAll(/icon:\s*"([a-z0-9-]+)"/g)) used.add(m[1]);
}
const missing = [...used].filter((n) => !names.includes(n));
if (missing.length) {
  console.error("MISSING from ICONS list: " + missing.join(", "));
  process.exit(1);
}
console.log("all referenced icons present");
